### ISSUE TITLE
Tracking Bootstrap layout implementation

### ISSUE THREAD

**Issue by Mandily** [solidusio/solidus#1153]
While we're in the process of converting Solidus core pages to the new bootstrap layouts, I'd like to keep track of what's been done and what's still outstanding. When a page is complete, we'll mark it with a strikethrough.

### Orders
- [ ] Order listing
 - [ ] New order
 - [ ] Specific order/Shipments
 - [ ] Cart
 - [ ] Customer
 - [ ] Adjustments
   - [ ] Edit adjustments
 - [ ] Payments
 - [ ] RMA
 - [ ] Customer returns
   - [ ] New customer return
 - [ ] Cancel inventory

### Products
- [ ] Product listing
 - [ ] New product
 - [ ] Specific product
 - [ ] Product details
 - [ ] Images
   - [ ] Edit Image
 - [ ] Variants
   - [ ] Edit variant
 - [ ] Product properties
 - [ ] Stock management
- [ ] Option types
  - [ ] Edit option type
- [ ] Properties
  - [ ] Edit property
- [ ] Prototypes
  - [ ]  Edit prototype
- [ ] Taxonomies
  - [ ] New Taxonomy
  - [ ] Edit Taxonomy
  - [ ] Edit Taxon
- [ ] Taxons

### Reports
- [ ] Report listing
 - [ ] Individual report

### Settings
- [ ] General settings
 - [ ] Analytics trackers
   - [ ] New analytics tracker
- [ ] Payments
 - [ ] New payment method
 - [ ] Edit payment method
- [ ] Areas/Zones
   - [ ] New zone
   - [ ] Edit zone
 - [ ] Countries
  - [ ] New country
  - [ ] Edit country
 - [ ] States
 - [ ] Edit state
- [ ] Taxes/Tax categories
  - [ ] New tax category
  - [ ] Edit tax category
 - [ ] Rates
  - [ ] New tax category
  - [ ] Edit tax category 
- [ ] Checkout/Refund reasons
   - [ ] New refund reason
 - [ ] Reimbursement types
 - [ ] Return reasons
   - [ ] New RMA reason
   - [ ] Edit return reason
 - [ ] Adjustment reasons
   - [ ] New adjustment reason
   - [ ] Edit adjustment reason
- [ ] Shipping/Shipping method
   - [ ] New shipping method
   - [ ] Edit shipping method
 - [ ] Shipping categories
   - [ ] New shipping category
   - [ ] Edit shipping category
 - [ ] Stock locations
   - [ ] New stock location
   - [ ] Edit stock location
 - [ ] Stock transfer
   - [ ] New stock transfer
   - [ ] Edit stock transfer

### Promotions
- [ ] Promotions list
 - [ ] New promotions
 - [ ] Edit promotions
- [ ] Promotions categories
 - [ ] New promotion category
 - [ ] Edit promotion category

### Stock 
- [ ] Management
- [ ] Transfers
 - [ ] New Stock Transfer
 - [ ] Edit Stock Transfer

### Users
- [ ] User list
 - [ ] New User
 - [ ] Edit User

**Comment by mtylty** [comment]
is this going to be completed with one PR per page?

**Comment by cbrunsdon** [comment]
@mtylty I think its more of a "one PR per what makes sense". Would be nice if it was a small enough unit of work that was quick to review, but in some cases it might make sense to cut through multiple things at once.

**Comment by Murph33** [comment]
With regards to that I've done some preliminary work using the layouts @graygilmore is introducing in #1114 on the index views without any forms and it's just been adding one line of `<% admin_layout 'full-width' %>` and removing references to the old skeleton system.

**Comment by omnistegan** [comment]
I've spent some time working with @Mandily on the product related pages. I'm still working through a few small improvements and then I'll submit a PR for the product edit page and solicit comments.

**Comment by JDutil** [comment]
I believe the admin UI has been updated so this issue could be closed as it's out of date. /cc @jacobherrington @spaghetticode @gmacdougall
