### ISSUE TITLE
Rails 5.2

### ISSUE THREAD

**Issue by jhawthorn** [solidusio/solidus#2460]
Rails 5.2 is in beta, and we should get ready for it

Gems needing fixes:
* [ ] [polyamorous](https://github.com/activerecord-hackery/polyamorous) is broken
* [ ] [ransack](https://github.com/activerecord-hackery/ransack) is broken
* [x] acts_as_list has an open PR to fix deprecations swanandp/acts_as_list#294
* [x] [friendly_id](https://github.com/norman/friendly_id) has an open PR to fix deprecations norman/friendly_id#849
* [x] [awesome_nested_set](https://github.com/collectiveidea/awesome_nested_set) has an open PR to fix deprecations collectiveidea/awesome_nested_set#383
* [ ] [cancancan](https://github.com/cancancommunity/cancancan) is broken (as of rails 5.2.0.rc1)

Gems needing only gemspec dependency bumps:
* [ ] font-awesome-rails
* [ ] paranoia
* [ ] canonical-rails

Solidus:
* [x] #2465
* [x] #2563

**Comment by halo** [comment]
I believe polyamorous has been fixed in https://github.com/activerecord-hackery/polyamorous/pull/28 and ransack has been fixed in https://github.com/activerecord-hackery/ransack/pull/868

**Comment by damienlethiec** [comment]
Hi @jhawthorn 

Sorry to come back to you! Rails 5.2.0.rc2 is out (http://weblog.rubyonrails.org/2018/3/20/Rails-5-2-RC2/). Any news about the status of the gems Solidus depends on? Do you know when will we be able to use Solidus with Rails 5.2?

Thanks a ton :)

**Comment by damienlethiec** [comment]
Hello @jhawthorn :)

Any news?

Thanks a lot!! :)

**Comment by davideghz** [comment]
up

**Comment by benbonnet** [comment]
just tried on 5.2, source in the gemfile from master; getting the following :

```
solidus was resolved to 2.6.0.alpha, which depends on
      solidus_core (= 2.6.0.alpha) was resolved to 2.6.0.alpha, which depends on
        actionpack (~> 5.1.0)
```
