### ISSUE TITLE
Add orders index page to the admin

### ISSUE THREAD

**Issue by rainerdema** [solidusio/solidus#5356]
**Desired Behavior**

- [x] Add orders/index component with order list table. #5347
- [x] Include filters that match the old version. #5347
- [x] Introduce new scope filters. #5516
- [x] Incorporate a search bar. #5347
