### ISSUE TITLE
[SEO / Structured Data] Define main taxon for usage in breadcrumbs

### ISSUE THREAD

**Issue by fthobe** [solidusio/solidus#6047]
## Issue
Currently breadcrumbs are not necessarily generated correctly as any of multiple taxons configured with the product can be picked to load them in the store front. 

## Desired Behaviour
Breadcrumbs are a keyword ranking factor and therfore a factor in the determination of relevant keywords by search engines. Merchants should have the possibility to enforce one taxon as primary for the generation of breadcrumbs and that taxon should be rendered with ancestors as breadcrumb trail. 

## Task

- [x] add a column to products to identify **one** primary breadcrumb (column name: breadcrumb_taxon)
- [x] allow the primary breadcrumb to be selected on the admin panel from the available taxon using identical form fields to current taxons form field (Label: "Breadcrumb Taxon"; Info: "Breadcrumb Taxon", Description: "If you want to use a specific taxon to generate the breadcrumbs you can select it here. This is particularly useful if you use more than one taxon and want to emphasise certain keywords to search engines.") 
- [x] Add the field to the API as "breadcrumb_taxon"
- [ ] Implement the breadcrumbs on the Starter_Frontend mantaining the existing logic to construct ancestors and add an if validation to use the "breadcrumb_taxon" to generate the breadcrumbs if it is present
- [x] Implement tests
- [ ] Follow discussion below if design changes are required.

## Related Issues
Concerns also: [Starter Frontend Issue #130](https://github.com/solidusio/solidus_starter_frontend/issues/130)

## Previous Conversations with maintainers
> Every shop I worked with has a different understanding of what the main taxonomy (most of the time referred to as "Category") is. Some refer to as the "Storefront" taxonomy, some call it "Navigation", etc. I can see that there is an urge for at least something that is been used as the main product category.

> We could make it configurable and default to a taxonomy with a "Category" name or add a flag to the taxonomies table (ie. main_category).

> I am open to suggestions.

If introducing a `main_taxon` is ok for everybody that's fine for me and we could implement that.

**Comment by kennyadsl** [comment]
What about a flag on the taxonomy, similar to `default_for_breadcrumbs`. "Main" doesn't have a good semantic IMHO.

**Comment by fthobe** [comment]
Hi @kennyadsl do you mean that a taxon is flagged as a primary taxon for all products related? Sorry I am trying to understand your approach better as currently the issue is that there are too many taxons and I feel we just shift the problem instead of solving it if we don't create a simple 1 product 1 taxon relation to generate the breadcrumbs.

**Comment by kennyadsl** [comment]
`use_for_breadcrumbs`?

**Comment by fthobe** [comment]
Man, whatever makes you happy and creates something that is merged.

Follow the breadcrumbs to reach the PR... 🍞

**Comment by kennyadsl** [comment]
You get this started by complaining for the long column name! 😆 
For `breadcrumbs_taxon`, my point is that you are adding the column to the taxon table, it's useless to repeat that that value refers to a taxon. You'll have `taxon.breadcrumb_taxon`, which is redundant.  

I'm ok with whatever name, just use your common sense.

**Comment by jarednorman** [comment]
We're talking about marking which _taxonomy_ and not _taxon_ should be used for breadcrumbs, right? I think calling the column (on the `spree_taxonomies` table) `breadcrumbs` is sufficient.

**Comment by tvdeyen** [comment]
> > You get this started by complaining for the long column name! 😆
> > For `breadcrumbs_taxon`, my point is that you are adding the column to the taxon table, it's useless to repeat that that value refers to a taxon. You'll have `taxon.breadcrumb_taxon`, which is redundant.
> > I'm ok with whatever name, just use your common sense.
> 
> Honestly we went for a selector.

What is "a selector" in this context?

**Comment by fthobe** [comment]
I do not think having this value in the taxonomy is a smart move. It's a value of a product, if we have to breadcrumb taxonomies associated to a product we are again at the beginning of the Problem of having to many taxons. Could we please make this a column on the product and not a taxon issue, because it just isn't. 

The solution taken for Brands was already allowing multiple Brands on one product which i do not think was smart but the Risk here to make mistakes in data entry is Little to none. With this topic I feel much much stronger.

**Comment by tvdeyen** [comment]
> I do not think having this value in the taxonomy is a smart move. It's a value of a product, if we have to breadcrumb taxonomies associated to a product we are again at the beginning of the Problem of having to many taxons. Could we please make this a column on the product and not a taxon issue, because it just isn't.
> 
> The solution taken for Brands was already allowing multiple Brands on one product which i do not think was smart but the Risk here to make mistakes in data entry is Little to none. With this topic I feel much much stronger.

Can you give an example of how you would imagine this implementation on the product level? Since taxonomies are the way to "categorize" products in any categorization (brands, categories, navigations) it feels more natural to implement it on that level.

**Comment by fthobe** [comment]
Sure, I sometimes struggle to align my language with yours and I apologies for that. 

So what Kenny and Jared suggest is to my understanding add a "is main breadcrumb" flag to a taxon and automatically define this taxon as breadcrumb if it's present on a product. 

I understand that this solution might seem tempting for the simplicity. 

The issue with that is that it doesn't solve the problem: 
- If we add two of them to a product we are at the starting point 
- (sub-)taxons might be many and not distinct enough to keep track of which I have added

This could of course be mitigated by some logic to check if multiple breadcrumb taxons are present, but it seems to me we create a lot of logic to mitigate a problem when we could just create another column of the product to be linked of any of the taxons in a matter that belongs to one. 

I feel that having brand taxons in the manor we did was bending logic, here we are really breaking the purpose of the implementation by shifting distinct product features into taxons. 

If I misunderstood please correct me and we can have this out of the door by Friday.

**Comment by jarednorman** [comment]
If someone erroneously put a product in two different taxons in their breadcrumbs taxonomy, you'd just take the first one. It's really not a serious problem.

**Comment by fthobe** [comment]
It's confusing, is there any particular reason why it's better having a column on the taxon rather than a column on the product?

I already found the brands in taxonomies hard but still manageable, here you are really loosing me on logic.

**Comment by kennyadsl** [comment]
@fthobe can you explain your proposal better? Is it adding a different taxon on each product? How is the process to add them? Manual or automatic?

**Comment by fthobe** [comment]
Generally you want the furthest level of taxon for primary breadcrumb trail. 

Google encourages ONE breadcrumb 
I know of some iterations of Bing (Bing / Yahoo have different versions of the engine per language space, English is usually up to date, others are trailing usually by 1-2 major versions), dropping everything but the first.

To give you a good example where that might be problematic: 

Imagine you sell All Star Sneakers, the basketball shoe of the 80ies (sneaker), the Nike Air Jordan Basket ball shoes and a Pair of Adidas Stan Smith Tennis Shoes. 

Nike Air Jordan would clearly go in the Basket Ball category and here we go, but what about the All Star and the Stan Smith. Nobody who ever throw a ball will buy All Star sneakers for Basketball, but the Stan Smith is really problematic, it's a (more or less valid) tennis shoe but it sells as a fashion accessory as vintage shoe (actually much much more), you want the all star and the Stan smith rank as (vintage-)sneaker, but it no way that doesn't mean that there aren't many many basketball shoes that no mindful individual would wear as regular day to day shoe. 

In fact what google ENCOURAGES is having one primary breadcrumb trail and (optional) alternative ones according to where you desire structurally allocate your product. 

If we want to cover the basic here:
- ONE DEFINITIVE primary breadcrumb

If we want to go the extra mile: 
- all non primary breadcrumbs below the content section of the product above the footer

For who wants to read it:
[https://www.searchenginejournal.com/matt-cutts-explains-can-use-multiple-breadcrumbs-page-without-confusing-googlebot/95333/](https://www.searchenginejournal.com/matt-cutts-explains-can-use-multiple-breadcrumbs-page-without-confusing-googlebot/95333/)

Deep dive:
[Implementation](https://developers.google.com/search/docs/appearance/structured-data/breadcrumb)

**Comment by fthobe** [comment]
Regarding editing them: 

> How is the process to add them? Manual or automatic?

Well, AI is on the horizon, but actually most SEO is excel and tool based. I would go for admin interface + api here.

**Comment by kennyadsl** [comment]
Ok but what’s the UX for the admin here?

The problem is clear but I struggle to understand your proposal in terms of what’s the experience for the admin user managing the breadcrumbs with the product level field. 

Maybe you can try to build some rough mockup quickly to let us understand your idea?

**Comment by fthobe** [comment]
### Current interface
The current interface for taxons is absolutely great, as it gives a more profound understanding of the taxon currently selected. 
It is amazing because it displays the taxon and ancestors in a concise and easy to understand way that allows to comprehend the location of the individual taxon without actualy beeing in the taxon menu. 
Many systems did not find such an elegant solution.
Just to give you an idea what we have to work with on BC: 
![Image](https://github.com/user-attachments/assets/0c0c75f8-1b8a-4b9f-bd67-11b9e5d20cf7)

### What should be done
**For breadcrumbs**
Given that the current interface is actually awesome, let's reuse it limited to one taxon. 
<img width="1378" alt="Image" src="https://github.com/user-attachments/assets/54b26b86-607d-4466-af65-c95808127a5d" />

And as we are good citizens, with help notice: 

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/34c20140-4885-4e75-ac23-6d63ea3726d9" />

**Comment by fthobe** [comment]
Do we want to use this chance to also clean up the form order a bit? 

We could concentrate all rarely changed data in one block: 
## Block 1: Basic Catalogue Data

1. Name
2. Taxons
3. Description
4. Option Types

## Block 2: Search Engine Optimization
1. Meta Title 
2. Slug
3. Breadcrumb Taxon
4. Meta Keywords
5. Meta Description

# Visual Proposal 

<img width="1042" alt="Image" src="https://github.com/user-attachments/assets/92b4f42e-d90b-4eb2-996c-5f3d45fd12da" />

**Comment by fthobe** [comment]
@tvdeyen please don't close my issues before they are fully solved, we still have the frontend PR pending on this?

**Comment by kennyadsl** [comment]
GitHub closes issues automatically when they are linked to PRs like this:

![Image](https://github.com/user-attachments/assets/41d9ce76-c5e1-48da-8bf2-573e936c84bc)

The poor Thomas is only guilty of merging the PR.

**Comment by fthobe** [comment]
@kennyadsl @tvdeyen thanks, this is closed now.
