### ISSUE TITLE
Solidus VAT Roadmap 

### ISSUE THREAD

**Issue by mamhoff** [solidusio/solidus#989]
For now, this roadmap is work in Progress. 

Solidus' VAT system has been very crazy, and I'm working slowly on reducing that crazyness. In the past weeks, I've been slowly moving parts of the taxation system into service objects, as well removing some duplicate and terse logic. 

Much of the refactoring is done, from here on we're mostly looking at extracting logic into service objects and adding functionality for handling VAT pricing more elegantly.
### Refactoring
- [x] https://github.com/solidusio/solidus/pull/529 (pull in some Spree work)
- [x] https://github.com/solidusio/solidus/pull/530 (Try simplifying zones)
- [x] https://github.com/solidusio/solidus/pull/650 (add real-life scenario specs for VAT and normal tax)
- [x] https://github.com/solidusio/solidus/pull/657 (Use Zone#contains? rather than checking for zone equality)
- [x] https://github.com/solidusio/solidus/pull/684 (Minor refactoring)
- [x] https://github.com/solidusio/solidus/pull/705 (Clean up of very strange logic for rate selection)
- [x] https://github.com/solidusio/solidus/pull/706 (Have `ReturnItem`s use `amount` instead of `pre_tax_amount`, making the return items having to know much less about taxes)
- [x] https://github.com/solidusio/solidus/pull/783 (Find zones by address, much faster than previous ways)
- [x] https://github.com/solidusio/solidus/pull/913 (Speed up application of calculcated tax adjustments)
- [x] https://github.com/solidusio/solidus/pull/914 (Improve I18n for tax adjustment labels)
- [x] https://github.com/solidusio/solidus/pull/915 (Make a method private, enabling #980)
- [x] https://github.com/solidusio/solidus/pull/980 (Contain bizarre logic in a calculator)
- [x] https://github.com/solidusio/solidus/pull/998 (Make all line items always have their order's currency)
### Bugfixes
- [x] https://github.com/solidusio/solidus/pull/901 (Prevent rounding errors in some circumstances)
- [x] https://github.com/solidusio/solidus/pull/941 (Really prevent those errors forever)
- [x] https://github.com/solidusio/solidus/pull/969 (Have `Spree::Product#prices` return all prices)
### Introduce service objects
- [x] https://github.com/solidusio/solidus/pull/685 (Move taxation into new POROs instead of `TaxRate.adjust')
- [x] Add a configurable line item pricer class 
### Untangling of the "default zone"
- [x] https://github.com/solidusio/solidus/pull/933 (Relieve the default tax zone of cart taxation responsibilies, make cart behaviour store-dependent)
- [x] Replace the default zone with a default tax location and find rates by address only (much faster, more reliable)
### Necessary new features
- [x] Add prices and price selection for different VAT countries
- [x] Add an interface for administering the prices for different variants/countries/currencies 
- [x] Understandable documentation

**Comment by tvdeyen** [comment]
![Respect](http://i.giphy.com/xT9DPxPZnDcBMX6tAk.gif)

**Comment by mamhoff** [comment]
@gmacdougall @jhawthorn Here's a list of open tax-related PRs, in order of which one to merge first for the least amount of friction: 

### Core taxation system

[ ] #980 Move refunding logic into calculator
[ ] #904 Add Spree::ShippingRateTax

###  Pricing

[ ] #994 API for Line Item Pricers
[ ] #987 Historical prices

### Drive-by refactorings

[ ] #1007 Never set a line item's currency in strange ways.

**Comment by mamhoff** [comment]
@tvdeyen Could you edit out the GIF? I'm confused every time I look at it :)

**Comment by bbuchalter** [comment]
This issue seems quite out of date. Perhaps it's time to give it a freshening up in light of our intention to add related guides (https://github.com/solidusio/solidus/pull/1606)? I'd love for the guide to reference any further planned development.

**Comment by mamhoff** [comment]
I'll close this issue now as the refactoring in question is mostly done. The one point not tackled so far is time-aware tax rates, for which I'll create a new issue.
